"""add_otp_rate_limiting_fields

Revision ID: 68cfb4b2a5d0
Revises: 001
Create Date: 2025-11-18 13:38:56.462308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cfb4b2a5d0'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_resend_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_last_resent_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=app.features.auth.models.user.GUID(),
               existing_nullable=False)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('waitlist', sa.Column('name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_column('waitlist', 'created_at')
    op.drop_column('waitlist', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('waitlist', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=False)
    op.drop_column('waitlist', 'name')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=app.features.auth.models.user.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('users', 'otp_last_resent_at')
    op.drop_column('users', 'otp_resend_count')
    # ### end Alembic commands ###
