"""initial

Revision ID: c489e27dd5f2
Revises: 
Create Date: 2025-11-19 23:38:58.082983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c489e27dd5f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_resend_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_last_resent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_last_resent_at')
    op.drop_column('users', 'otp_resend_count')
    # ### end Alembic commands ###
